version: '2.2'

volumes:
  postgresql: ~
  rabbitmq: ~

networks:
  mistral: ~
  database: ~
  message-broker: ~

services:

  postgresql:
    image: postgres:10-alpine
    restart: unless-stopped
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: mistral
      POSTGRES_USER: mistral
      POSTGRES_DB: mistral
    healthcheck:
      test: "su postgres -c pg_isready"
      interval: 5s

  database-migration:
    build:
      context: .
      args:
        MISTRAL_VERSION: "${MISTRAL_VERSION:-mistral<2015}"
        GERRIT_REVIEW: "${GERRIT_REVIEW:-}"
    command: mistral-db-manage --config-file "/etc/mistral/mistral.conf" upgrade head
    networks:
      - database
    depends_on:
      postgresql:
        condition: service_healthy

  database-poulate:
    build:
      context: .
      args:
        MISTRAL_VERSION: "${MISTRAL_VERSION:-mistral<2015}"
        GERRIT_REVIEW: "${GERRIT_REVIEW:-}"
    command: mistral-db-manage --config-file "/etc/mistral/mistral.conf" populate
    networks:
      - database
    depends_on:
      database-migration:
        condition: service_started

  message-broker:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - "15672:15672"
    networks:
      - message-broker
    hostname: rabbitmq
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.81
      RABBITMQ_DEFAULT_USER: mistral
      RABBITMQ_DEFAULT_PASS: mistral
      RABBITMQ_DEFAULT_VHOST: mistral

  mistral-api:
    build:
      context: .
      args:
        MISTRAL_VERSION: "${MISTRAL_VERSION:-mistral<2015}"
        GERRIT_REVIEW: "${GERRIT_REVIEW:-}"
    ports:
      - "8989:8989"
    networks:
      - database
      - message-broker
      - mistral
    environment:
      MISTRAL_SERVER: api
    depends_on:
      database-migration:
        condition: service_started
      message-broker:
        condition: service_started

  mistral-engine:
    build:
      context: .
      args:
        MISTRAL_VERSION: "${MISTRAL_VERSION:-mistral<2015}"
        GERRIT_REVIEW: "${GERRIT_REVIEW:-}"
    networks:
      - database
      - message-broker
    environment:
      MISTRAL_SERVER: engine
    depends_on:
      mistral-api:
        condition: service_started

  mistral-executor:
    build:
      context: .
      args:
        MISTRAL_VERSION: "${MISTRAL_VERSION:-mistral<2015}"
        GERRIT_REVIEW: "${GERRIT_REVIEW:-}"
    networks:
      - message-broker
    environment:
      MISTRAL_SERVER: executor
    depends_on:
      mistral-api:
        condition: service_started

  mistral-event-engine:
    build:
      context: .
      args:
        MISTRAL_VERSION: "${MISTRAL_VERSION:-mistral<2015}"
        GERRIT_REVIEW: "${GERRIT_REVIEW:-}"
    networks:
      - database
      - message-broker
    environment:
      MISTRAL_SERVER: event-engine
    depends_on:
      mistral-api:
        condition: service_started

  mistral-notifier:
    build:
      context: .
      args:
        MISTRAL_VERSION: "${MISTRAL_VERSION:-mistral<2015}"
        GERRIT_REVIEW: "${GERRIT_REVIEW:-}"
    networks:
      - database
      - message-broker
    environment:
      MISTRAL_SERVER: notifier
    depends_on:
      mistral-api:
        condition: service_started

  cloud-flow:
    image: mcdoker18/cloud-flow:0.5.0
    restart: always
    networks:
      - mistral
    ports:
      - "8000:8000"
    networks:
      - mistral
    environment:
      CF_MISTRAL_URL: http://mistral-api:8989
    depends_on:
      mistral-api:
        condition: service_started
